site_name: Cyber Class 2022 
site_url: https://lazeroffmichael.github.io/teaching/

# Repository
repo_name: lazeroffmichael/teaching
repo_url: https://github.com/lazeroffmichael/teaching

# Remove edit button
edit_uri: ""

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - primary: light blue
      accent: blue
      toggle:
        icon: material/lightbulb 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  features:
    - navigation.instant # Don't reload
    - navigation.tabs # Tabs on top
    - navigation.tabs.sticky # Tabs stay on top

plugins:
  - mkdocs-video

markdown_extensions:
  # Admonition
  - admonition
  - pymdownx.details
  - pymdownx.superfences

  # Content tabs
  - pymdownx.tabbed:
      alternate_style: true

  # Cool checklists
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true

  # images
  - attr_list
  - md_in_html

nav:
  - Home: index.md
  - Summer 2022:
    - Thursday July 7th 2022: summer2022/07-07-22.md
    - Tuesday July 12th 2022: summer2022/07-12-22.md
    - Thursday July 14th 2022: summer2022/07-14-22.md
  - Contact: contact.md

